### ISSUE TITLE
link to download is broken!

### ISSUE THREAD

**Issue by albgen** [MicrosoftDocs/sql-docs.it-it#94]
link to download is broken!

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Scaricare SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/it-it/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs.it-it/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by mrutter** [comment]
I'm trying to download 18.3, EN, but the link does not work and it redirects to the Microsoft's site.

**Comment by srvbpigh** [comment]
Hello, @albgen
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by djtyger89** [comment]
I'm trying to download 18.3, EN, but the link does not work and it redirects to the Microsoft's site. The problem is not solven yet.

**Comment by vtontodonato-c** [comment]
DOwnload link is broken please, resolve the issue because 18.2 has several bugs and crash often on database diagram visualization

**Comment by AntonioFico** [comment]
https://docs.microsoft.com/it-it/sql/ssms/release-notes-ssms?view=sql-server-2017#previous-ssms-releases

Here you can find the download for the previous version

**Comment by landlogicit** [comment]
Correct link: https://go.microsoft.com/fwlink/?linkid=2105412

**Comment by dnethi** [comment]
Sorry for the confusion folks. We missed updating the links for non en-US regions. This is being done ASAP and the updated links should work in the next 1-2 days. 

thanks,
Dinakar

**Comment by mrutter** [comment]
@dnethi: I'm using the English link (not Italian), but it does not work.
Comparing the link on Microsoft Docs against the link suggested by @landlogicit, I found the issue in on the **linkid**: it should be **linkid=2105412** instead of linkid=2104251.

The link for the EN version (18.3.1) is: https://go.microsoft.com/fwlink/?linkid=2105412&clcid=0x409

Also, please note that there is a typo in Microsoft documentation:
Link: https://docs.microsoft.com/it-it/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017
See "Available languages (SSMS 18.3)", I read "SQL Server Management Studio 18.2:" while it should be "SQL Server Management Studio 18.3:".

**Comment by CeciAc** [comment]
Hello, @albgen
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/it-it/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
